<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <script>
        // promise의 특징
        /** 
            1. 항상 비동기로 처리 보장
        **/
        var promise1 = new Promise((resolve) => {
            console.log("inner promise");
            resolve(42);
        });
        promise1.then((value) => {
            console.log(value);
        });
        console.log("outer promise");

        /**
            2. then() : 새로운 promise 객체 반환
        **/
        var promise2 = new Promise((resolve) => {
            resolve(100);
        });
        var thenPromise = promise2.then((value) => {
            console.log(value);
        });
        var catchPromise = thenPromise.catch((error) => {
            console.error(error);
        });
        console.log(promise2 === thenPromise);
        console.log(thenPromise === catchPromise);


        // 1) then()으로 등록한 함수가 동시에 호출
        var aPromise = new Promise((resolve) => {
            resolve(100);
        });
        aPromise.then((value) => {
            return value * 2;
        });
        aPromise.then((value) => {
            return value * 2;
        });
        aPromise.then((value) => {
            console.log("1 : " + value);
        });
        // 2) then()으로 등록한 함수가 promise 체인의 순서대로 호출
        var bPromise = new Promise((resolve) => {
            resolve(100);
        });
        bPromise.then((value) => {
            return value * 2;
        }).then((value) => {
            return value * 2;
        }).then((value) => {
            console.log("2: " + value);
        });


        /** 3. 예외 처리가 되지 않는 onRejected **/
        function throwError(value) {
            throw new Error(value);
        };
        // onRejected가 실행되지 않음
        function badMain(onRejected) {
            return Promise.resolve(42).then(throwError, onRejected);
        };
        // 예외 발생시 onRejected 호출
        function goodMain(onRejected) {
            return Promise.resolve(42).then(throwError).catch(onRejected);
        };
        badMain(() => {
            console.log("BAD");
        });
        goodMain(() => {
            console.log("GOOD");
        });
    </script>
</body>
</html>